### ISSUE TITLE
Add Answers.io support

### ISSUE THREAD

**Issue by k06a** [twobitlabs/AnalyticsKit#29]
Twitter's Answers now have custom events :)

https://answers.io/answers

**Comment by twobitlabs** [comment]
Excellent, send us a pull request with it!

**Comment by chrispix** [comment]
Actually I've already implemented this. It was in beta so I hadn't merged the branch yet, but I guess it's publicly available now. I'll merge it this week.

https://github.com/twobitlabs/AnalyticsKit/tree/crashlytics-events

**Comment by twobitlabs** [comment]
#30
