### ISSUE TITLE
Optional providers

### ISSUE THREAD

**Issue by mohammad19991** [twobitlabs/AnalyticsKit#35]
What if I want to send some spacific events for Google analytics and not to all providers I have?

**Comment by twobitlabs** [comment]
We've faced this issue a few times, and resolved it by using the GA SDK directly, rather than adding it as an AnalyticsKit provider. I'm not sure there's an elegant solution for this using AK. If you have a suggestion, we'd be happy to discuss it.

**Comment by twobitlabs** [comment]
One other thing we've done is keep a reference to the GA Analytics Kit Provider and then call methods directly on that analytics kit provider so at least the api is the same as calling AnalyticsKit.logEvent...

**Comment by mohammad19991** [comment]
I ended up doing the same, I'm keeping a reference of GA Provider and call the methods directly! but I will think about something and refactor it to better way.
I will let you know if I found better way to do it :)
