### ISSUE TITLE
Cannot create __weak reference in file using manual reference counting

### ISSUE THREAD

**Issue by kdawgwilk** [twobitlabs/AnalyticsKit#39]
Xcode 7.3 was released recently and now AnalyticsKit wont build because of this error on line #57 in AnalyticsKitDebugProvider.m

**Comment by kdawgwilk** [comment]
This points out that its weird this project is using manual reference counting but in the podspec are requiring iOS 8 or greater

**Comment by kdawgwilk** [comment]
One solution I found is here:
http://stackoverflow.com/questions/36147625/xcode-7-3-cannot-create-weak-reference-in-file-using-manual-reference-counting

**Comment by twobitlabs** [comment]
Opened #41 to update to ARC
