### ISSUE TITLE
Why is latest version not listed on Cocoapods Spec repo?

### ISSUE THREAD

**Issue by kdawgwilk** [twobitlabs/AnalyticsKit#40]
I pointed my pod to this repo to get the latest changes but am getting build errors in Xcode 7.3 listed in #39

**Comment by twobitlabs** [comment]
We don't officially support cocoapods. Currently the podspec won't lint, so I can't submit updates.

**Comment by twobitlabs** [comment]
If you're more familiar with cocoapods and are interested in getting the podspec working again, we would welcome a PR.
