### ISSUE TITLE
AnalyticsKitProvider should be public so consumers can write their own providers

### ISSUE THREAD

**Issue by kdawgwilk** [twobitlabs/AnalyticsKit#46]
I am wanting to create my own provider for Analytics kit for internal use and don't have visibility to the AnalyticsKitProvider protocol to conform too

**Comment by twobitlabs** [comment]
We should probably move the protocol into its own swift file. It's currently in AnalyticsKit.swift here:

https://github.com/twobitlabs/AnalyticsKit/blob/master/AnalyticsKit.swift

**Comment by kdawgwilk** [comment]
I fixed this as well as many many other things in my PR here #47

**Comment by twobitlabs** [comment]
Fixed in #47
