### ISSUE TITLE
Podspec not up to date

### ISSUE THREAD

**Issue by jimidobson** [twobitlabs/AnalyticsKit#53]
The latest source of the podspec seem to support Crashlytics, but the most recent cocoapod as indicated via` pod search AnalyticsKit` does not provide it as a subspec. Is this an oversight, or is this coming in a future update?

**Comment by twobitlabs** [comment]
Cocoapods is not officially supported, and we've had trouble updating the cocoapods repo. When we try to `pod trunk push`, we get an error saying `The 'Pods-App' target has transitive dependencies that include static binaries`.

We do not use AnalyticsKit with Cocoapods, but my understanding is that it works if you point the pod to the github repo:

```
pod 'AnalyticsKit', :git => 'https://github.com/twobitlabs/AnalyticsKit.git'
```
